### ISSUE TITLE
Not generating Config type definitions

### ISSUE THREAD

**Issue by revmischa** [sst/sst#1985]
Maybe I'm missing a step, but when I define Parameters they do not appear to be added to ConfigType.

```
Error: backend/src/db/client.ts(12,28): error TS2339: Property 'DB_SECRET_ARN' does not exist on type 'ConfigType'.
Error: backend/src/db/client.ts(23,12): error TS2339: Property 'PRISMA_CONNECTION_LIMIT' does not exist on type 'ConfigType'.
```

Error: https://github.com/jetbridge/sst-prisma/runs/7943547033?check_suite_focus=true

Definition: https://github.com/jetbridge/sst-prisma/pull/24/files#diff-a1c29b15546e1ef01591f307dc9358c0ebcb120a3eaa3a53be3072883d3b69e9

**Comment by cmaycumber** [comment]
Also running into this issue - we're working in a mono repo that's hoisting dependencies so that might have something to do with our issue.

**Comment by revmischa** [comment]
I believe my problem is that I have 
```
    "types": ["vitest/globals"],
```
in my tsconfig.json

I haven't figured out how to make it play nice with the generated type defs file yet.

**Comment by cmaycumber** [comment]
That makes sense, I could see my tsconfig also looking at the wrong files because I do see them generated in the node_modules folder

**Comment by revmischa** [comment]
I posted a lot of notes on trying to figure this out on the SST discord: https://discord.com/channels/983865673656705025/1010706582205648970

**Comment by revmischa** [comment]
If I do:
```ts
    "types": ["vitest/globals", "@types/serverless-stack__node"], // or "@types/serverless-stack__node/config"
```

Then I get errors when first building a project (like in CI) because the type defs aren't generated yet.
When I run `sst build` it requires AWS credentials, I am unclear as to why, but it's not a good dev experience for a starter kit or CI flow.

I was thinking to try a index.d.ts file containing `/// <reference types="@types/serverless-stack__node" />` but I haven't had luck with that approach either so far.

Even with the explicit addition of sst/node in `types` I still get type errors
![image](https://user-images.githubusercontent.com/245131/186745044-c39234b2-6742-4969-b7e1-19de97e01195.png)

**Comment by bestickley** [comment]
@revmischa, any resolutions on this?

**Comment by revmischa** [comment]
> @revmischa, any resolutions on this?

No I never got it working

**Comment by fwang** [comment]
@bestickley which sst version are you using? And do you see the types generated in `node_modules/@types/serverless-satck__node`?

**Comment by bestickley** [comment]
@fwang, I'm using 1.15.16. The problem that this issue is describing is not what I'm experiencing. Please see [this](https://discord.com/channels/983865673656705025/1034842628010823760) discord thread for more info. Essentially I'm trying to setup my stacks or infra within a sub-folder with pnpm but SST Config assumes stacks are a part of the root folder using npm (allowing phantom dependencies). I need to figure out a way to import my the type definitions which are correctly being created in infra/node_modules into core/node_modules. If you have any thoughts, please comment in thread, I don't want to hijack this issue. Thanks for checking!

**Comment by patricknazar** [comment]
I just fixed this issue by upgrading *the version of @serverless-stack/node in my services directory*! `npm i @serverless-stack/node` under services, for that particular `package.json`. As per [the resource binding docs](https://docs.sst.dev/resource-binding#quick-start) `"You'll also need to install the node package in the services/ directory."`

I figured the code was out of sync and it was. Now after running `sst start` a bunch of new lines appeared in `@serverless-stack/node/config` and yeah.. woohoo~

**Comment by revmischa** [comment]
I installed `@serverless-stack/node@1.17.1` in my services dir but I still don't see types appear, using pnpm

**Comment by patricknazar** [comment]
> I installed `@serverless-stack/node@1.17.1` in my services dir but I still don't see types appear, using pnpm

Have you tried restarting `sst start`? Have you also updated sst from the root with `sst update`?

**Comment by revmischa** [comment]
> > I installed `@serverless-stack/node@1.17.1` in my services dir but I still don't see types appear, using pnpm
> 
> Have you tried restarting `sst start`? Have you also updated sst from the root with `sst update`?

Yes, but `sst update` doesn't seem to do anything when using pnpm

**Comment by patricknazar** [comment]
@revmischa Apparently pnpm isn't currently supported #854

**Comment by bestickley** [comment]
@revmischa, with pnpm, node_modules aren't all hoisted to a global node_modules directory (although there you can "shamefully" hoist). SST's env vars intellisense set up depends on this hoisting. In order to use SST env vars with pnpm, you need to have your function constructs and function code share the same package.json with `@serverless-stack/node`. A fix for this would be fore `Function` to support something like [typePaths](https://docs.sst.dev/constructs/v0/ViteStaticSite#typespath). I've created a feature request [here](https://github.com/serverless-stack/sst/issues/2218).

@patricknazar, you're correct that PNPM isn't officially supported, but it can be used with the SST with some challenges. My feature request above will reduce one of the major challenges.

**Comment by pablocompagni-contractorvp** [comment]
I've just run into the same problem, but not with pnpm, just npm. In my case the application builds and deploys fine from my local computer, but then it fails to deploy from a CI.

What I noticed is that the `.sst/types` folder only gets generated when running `sst dev`, neither `sst build` nor `sst deploy` generates that. So I just versioned into git the types folder, while excluding everything else, and it works great.

**Comment by robinxb** [comment]
> 

Same here, this is different from what docs descript. I think the best way is to fix this issue from SST.

**Comment by jayair** [comment]
Hmm you shouldn't have to commit that dir. Can you post the issue you are having in #help on Discord?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
