### ISSUE TITLE
Cannot delete Auth Resource

### ISSUE THREAD

**Issue by ian-pascoe** [sst/sst#3499]
I am receiving this error when trying to delete the SST Auth resource:

```Received response status [FAILED] from custom resource. Message returned: User: arn:aws:sts::008193302444:assumed-role/...-Auth-CustomResourceHandlerServ-LC2ZFlSsHCBx/... is not authorized to perform: ssm:DeleteParameters on resource: arn:aws:ssm:us-east-1:008193302444:parameter/sst/.../ip-dev/Auth/auth/publicKey because no identity-based policy allows the ssm:DeleteParameters action```

I have to manually go into cloud formation and delete the resource.

---

If you've already posted your issue on Discord, make sure to leave a link to it here.

**Comment by ekrata-main** [comment]
Are you using the latest version of sst? I believe this has been fixed in #3417

**Comment by ddanielgc** [comment]
npx sst update? I am still having the issue, even after updating the sst package.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
